version: "3"
services:
  virtualcrypto_postgres:
    image: postgres
    env_file: postgres.env
    ports:
      - "5430:5430"
    volumes:
      - pgsql-virtualCrypto-data:/var/lib/postgresql/data
    container_name: "virtualcryptodb"
    command: -p 5430
  virtualcrypto:
    environment:
      - BOT_TOKEN
    env_file: postgres.env
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: "virtualCrypto"

volumes:
  pgsql-virtualCrypto-data:
